@startuml

header
Work in progress.
endheader

title Device Init via DDF

!include skinparams.txt

scale 1.25

hide empty members

class Device

Device : state = Get DDF

class "DDF Loader" as DeviceDescriptions {
	+handleEvent()
}

interface "DDF Init" as DDFInit << (M,#b4c7d1) >> {
    +DEV_InitDeviceFromDescription()
}

interface "Device Compat" as DeviceCompat << (M,#b4c7d1) >> {
	+DEV_InitCompatNodeFromDescription()
}

class Plugin {
	+DEV_AddResource()
}

Device -[#444444]down-> DeviceDescriptions : Init Request\nEvent
DeviceDescriptions -[#444444]up-> Device : Init Response\nEvent

DeviceDescriptions -right-> DDFInit : {Device*, DDF}

DDFInit --> DeviceCompat
DeviceCompat --> Plugin : Add Sensor or LightNode

caption Async execution path when a Device and its\nSub-Devices are initialized from a DDF.

@enduml